services:
  app:
    build: .
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - db_data:/app/back/data
      - ./datasets:/app/datasets
    restart: unless-stopped

volumes:
  db_data:
